name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2

      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

      - name: Source nvm
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

      - name: Use Node.js 18.18.0
        run: nvm install 18.18.0 && nvm use 18.18.0

      - name: Sync Files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            echo "start command"
            cd /home/ubuntu/ame-react-frontend && git pull && npm install && npm run build && pm2 restart 0
