name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get Lastest Code
        uses: actions/checkout@v2
      - name: Use Node.js 18.18.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - name: Sync Files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            echo "start command"
            cd /home/ubuntu/ame-react-frontend && git pull && npm install && npm run build && pm2 restart 0
